### ISSUE TITLE
Building on Windows causes error

### ISSUE THREAD

**Issue by brunoanc** [Danielmelody/ispc-texcomp-rs#4]
When building on Windows with the MSVC toolchain and without the `--features=ispc` option, I get the following error:
```
error: could not find native static library `kernelx86_64-pc-windows-msvc`, perhaps an -L flag is missing?
```

**Comment by Danielmelody** [comment]
Should be fixed now, seems github has limit my git lfs storage and trying to charge from it, shame on them.
I replaced all my lfs objects with normal git objects with a breaking history rewritten, now it should be built on windows.

**Comment by Danielmelody** [comment]
Besides, do not run `cargo test` on windows now, as the astc kernel currently not support well, I encountered a cpp-related cross platform issue. `cargo run --example main --features=ispc` should work well.

**Comment by Danielmelody** [comment]
@PowerBall253 I have setup a windows lib deployment [workflow](https://github.com/Danielmelody/ispc-texcomp-rs/blob/master/.github/workflows/publish.yml) through github actions, seems ispc cannot really do cross compilation on just one host machine. You can only build x86_64-pc-windows-msvc.lib and i686-pc-windows-msvc.lib on windows with msvc toolchain, the rust side however has a great support for cross compilation.
Thanks to github actions, we can build windows and unix libs respectively, feel free to improve our automatical workflows.

**Comment by Danielmelody** [comment]
@PowerBall253 Closing this, if you still have a problem, feel free to reopen it.

**Comment by brunoanc** [comment]
Seems to work with the latest version, thanks!
